export const aboutMeList = [
  "Trans Man",
  "Trans Woman",
  "Non Binary",
  "Women",
  "Black",
  "Native American",
  "Caucasian",
  "Pacific Islander",
  "Hispanic or Latino",
  "East Asian",
  "South Asian",
  "Southeast Asian",
  "Central Asian",
  "Western Asian",
  "Single",
  "Married",
  "Widowed",
  "Divorced",
  "Newlywed",
  "Pregnant",
  "Trying to Conceive ",
  "New Parent",
  "Parent",
  "Student",
];

export const myHealthList = [
  "Endometriosis",
  "PCOS",
  "Uterine Fibroids",
  "Interstitial Cystitis",
  "Recurrent Bacterial Vaginosis",
  "Recurrent UTIs",
  "Recurrent Yeast Infections",
  "Infertility",
  "Miscarriage",
  "IVF",
  "Adenomyosis",
  "Endometrial Polyps",
  "IBS",
  "Pelvic Adhesions",
  "Fibromyalgia ",
  "Pelvic Congestion Syndrome",
  "Asthma",
  "Allergies",
  "Crohn's",
  "Epilepsy",
  "Haemophila",
  "HIV/AIDs",
  "Hypertension",
  "Lupus",
  "Multiple Sclerosis",
  "Parkinson's disease",
  "Ulcerative Colitis",
  "Chronic Fatigue Syndrome",
  "Fibromyalgia",
  "Celiac",
  "Rheumatoid Arthritis",
  "Crohn's Disease",
  "Lyme Disease",
  "Cardiac Conditions",
  "Thyroid Conditions",
  "Sinusitis",
  "Psoriasis",
  "Parkinson's Disease",
  "Osteoporosis",
  "Migraine",
  "Lou Gehrig's Disease",
  "Kidney Disease",
  "Cerebral Palsy",
  "Bipolar Mood Disorder",
  "Schizophrenia",
  "Depression",
  "Anxiety",
  "OCD",
  "PTSD",
  "Social Anxiety",
  "Postpartum Depression",
  "Body Dysmorphia ",
  "Anorexia ",
  "Bulimia",
  "Binge Eating",
  "Painful Periods",
  "Painful Sex",
  "Painful Urination",
  "Pelvic Pain",
  "Heavy Periods",
  "Irregular Periods",
];

export const howCanIHelpList = [
  "Diagnosis",
  "Symptoms",
  "Treatments",
  "Doctors",
  "Surgeons",
  "Nutritionists",
  "Therapists",
  "Physical Therapists",
  "Holistic Medicine",
  "Medications",
  "General Advice",
  "Support",
];
