export const dummyJSON = [
  {
    question: 'Were you diagnosed with endometriosis?',
    answers: ['Yes', 'No'],
    isMultiSelect: false,
  },
  {
    question:
      'Please check all the symptoms below that you experienced at least once in the past few months.',
    answers: [
      'Heavy / Extreme menstrual bleeding',
      'Menstrual pain (Dysmenorrhea)',
      'Painful / Burning pain during intercourse (Dyspareunia)',
      'Pelvic pain',
      'Irregular / Missed periods',
      'Cramping',
      'Abdominal pain / Pressure',
      'Back pain',
      'Painful bowel movements',
      'Nausea',
      'Menstrual clots',
      'Infertility',
      'Painful cramps during period',
      'Pain / Chronic pain',
      'Diarrhea',
      'Long menstruation',
      'Constipation / Chronic constipation',
      'Vomiting / constant vomiting',
      'Fatigue / Chronic fatigue',
      'Painful ovulation',
      'Stomach cramping',
      'Migraines',
      'Extreme / Severe pain',
      'Leg pain',
      'Irritable Bowel Syndrome (IBS)',
      'Syncope (fainting, passing out)',
      'Mood swings',
      'Depression',
      'Lower back pain',
      'Fertility issues',
      'Ovarian cysts',
      'Painful urination',
      'Headaches',
      'Constant bleeding',
      'Pain after intercourse',
      'Digestive / GI problems',
      'IBS-like symptoms',
      'Anaemia / Iron deficiency',
      'Hip pain',
      'Vaginal Pain/Pressure',
      'Sharp / Stabbing pain',
      'Bowel pain',
      'Anxiety',
      'Cysts (unspecified)',
      'Dizziness',
      'Malaise / Sickness',
      'Abnormal uterine bleeding',
      'Fever',
      'Hormonal problems',
      'Bloating',
      'Feeling sick',
      'Decreased energy / Exhaustion',
      'Abdominal Cramps during Intercourse',
      'Insomnia / Sleeplessness',
      'Acne / pimples',
      'Loss of appetite',
    ],
    isMultiSelect: true,
  },
];

//  TODO: this is a temporary summ and thresholding algorithm
//  until we have the full dataset
export const endoAssessmentWeights = {
  'Heavy / Extreme menstrual bleeding': 0.59,
  'Menstrual pain (Dysmenorrhea)': 0.71,
  'Painful / Burning pain during intercourse (Dyspareunia)': 0.55,
  'Pelvic pain': 0.57,
  'Irregular / Missed periods': 0.4,
  Cramping: 0.6,
  'Abdominal pain / Pressure': 0.56,
  'Back pain': 0.49,
  'Painful bowel movements': 0.45,
  Nausea: 0.39,
  'Menstrual clots': 0.42,
  Infertility: 0.27,
  'Painful cramps during period': 0.6,
  'Pain / Chronic pain': 0.45,
  Diarrhea: 0.27,
  'Long menstruation': 0.3,
  'Constipation / Chronic constipation': 0.35,
  'Vomiting / constant vomiting': 0.16,
  'Fatigue / Chronic fatigue': 0,
  'Painful ovulation': 0.4,
  'Stomach cramping': 0.44,
  Migraines: 0.16,
  'Extreme / Severe pain': 0.39,
  'Leg pain': 0.25,
  'Irritable Bowel Syndrome (IBS)': 0.25,
  'Syncope (fainting, passing out)': 0.13,
  'Mood swings': 0.32,
  Depression: 0.3,
  'Lower back pain': 0.47,
  'Fertility issues': 0.18,
  'Ovarian cysts': 0.42,
  'Painful urination': 0.26,
  Headaches: 0.23,
  'Constant bleeding': 0.13,
  'Pain after intercourse': 0.39,
  'Digestive / GI problems': 0.3,
  'IBS-like symptoms': 0.34,
  'Anaemia / Iron deficiency': 0.27,
  'Hip pain': 0.24,
  'Vaginal Pain/Pressure': 0.33,
  'Sharp / Stabbing pain': 0.45,
  'Bowel pain': 0.22,
  Anxiety: 0.35,
  'Cysts (unspecified)': 0.35,
  Dizziness: 0.23,
  'Malaise / Sickness': 0.09,
  'Abnormal uterine bleeding': 0.09,
  Fever: 0.11,
  'Hormonal problems': 0.36,
  Bloating: 0.47,
  'Feeling sick': 0.26,
  'Decreased energy / Exhaustion': 0.44,
  'Abdominal Cramps during Intercourse': 0.32,
  'Insomnia / Sleeplessness': 0.24,
  'Acne / pimples': 0.29,
  'Loss of appetite': 0.14,
};
export const endoAssessmentWeightsSum = 19.33;
export const endoAssessmentWeightsLowThreshold = 3;
export const endoAssessmentWeightsMediumThreshold = 5.73;
export const endoAssessmentWeightsHighThreshold = 8;

//  Algorithm attribution required for the above:
//  Goldstein, A., Cohen, S. Self-report symptom-based endometriosis prediction using machine learning. Sci Rep 13, 5499 (2023). https://doi.org/10.1038/s41598-023-32761-8
