export const topicsList = [
  "Acne",
  "Iron-deficiency anemia",
  "Anorexia nervosa",
  "Anxiety disorders",
  "Asthma",
  "Autoimmune Diseases",
  "Bacterial Vaginosis",
  "Binge eating disorder",
  "Birth Control Methods",
  "Bladder Control / Urinary Incontinence",
  "Bladder Pain",
  "Bleeding Disorders",
  "Body Image",
  "Breast Cancer",
  "Breastfeeding",
  "Breast Reconstruction After Mastectomy",
  "Bulimia Nervosa",
  "Cancer",
  "Caregiver Stress",
  "Cervical Cancer",
  "Chronic Fatigue Syndrome / Myalgic Encephalomyelitis",
  "Chlamydia",
  "Chronic obstructive pulmonary disease",
  "Carpal tunnel syndrome",
  "Postpartum depression",
  "Depression",
  "Diabetes",
  "Domestic violence/abuse",
  "Douching",
  "Date rape drugs",
  "Eating Discorders",
  "Emergency birth control/emergency contraception",
  "Endometriosis",
  "Female genital mutilation or cutting",
  "Fibromyalgia",
  "Fitness",
  "Folic Acid",
  "Genital herpes",
  "Genital Warts",
  "Getting Active",
  "Gonorrhea",
  "Graves' disease",
  "Hashimoto's Disease",
  "Nutrition / Healthy Eating",
  "Healthy Weight",
  "Heart Disease",
  "HIV and AIDS",
  "Human papillomavirus",
  "Hysterectomy",
  "Inflammatory bowel disease",
  "Irritable bowel syndrome (IBS)",
  "Infertility",
  "Insomnia",
  "Lupus",
  "Mammograms",
  "Myalgic encephalomyelitis/chronic fatigue syndrome",
  "Menopause",
  "Menstrual Cycle (Period)",
  "Mental Health",
  "Migraine",
  "Myasthenia gravis",
  "Oral Health",
  "Osteoporosis",
  "Ovarian Cancer",
  "Ovarian Cysts",
  "Overweight, obesity, and weight loss",
  "Ovulation",
  "Pap and HPV tests",
  "Polycystic Ovary Syndrome (PCOS)",
  "Perimenopause",
  "Pelvic inflammatory disease (PID)",
  "Pelvic organ prolapse",
  "Pregnancy",
  "Premenstrual syndrome (PMS)",
  "Sexual Assault",
  "Sickle Cell Disease",
  "Sleep and your health",
  "Sexually transmitted infections",
  "Stress and your health",
  "Stroke",
  "Syphilis",
  "Thyroid Disease",
  "Trichomoniasis",
  "Uterine Cancer",
  "Uterine Fibroids",
  "Urinary Tract Infection",
  "Varicose veins and spider veins",
  "Relationships and Safety",
  "Viral Hepatitis",
  "Vaginal yeast infections",
];
