const SymptomsDir = {
  1: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg024MenstrualPain",
    Category: "Gastrointestinal",
    Name: "Abdominal Pain",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  2: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg017Stool",
    Category: "Gastrointestinal",
    Name: "Bloating",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  3: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg017Stool",
    Category: "Gastrointestinal",
    Name: "Blood in Stool",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  4: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg047Bubbles",
    Category: "Gastrointestinal",
    Name: "Burping",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  5: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg017Stool",
    Category: "Gastrointestinal",
    Name: "Constipation",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  6: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg017Stool",
    Category: "Gastrointestinal",
    Name: "Diarrhea",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  7: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg047Bubbles",
    Category: "Gastrointestinal",
    Name: "Farting",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  8: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg047Bubbles",
    Category: "Gastrointestinal",
    Name: "Heartburn",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  9: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg019Incontinence",
    Category: "Gastrointestinal",
    Name: "Incontinence",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  10: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg047Bubbles",
    Category: "Gastrointestinal",
    Name: "Indigestion",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  11: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg017Stool",
    Category: "Gastrointestinal",
    Name: "Mucus in Stool",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  12: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg025Vomiting",
    Category: "Gastrointestinal",
    Name: "Nausea",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  13: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg017Stool",
    Category: "Gastrointestinal",
    Name: "Painful Bowl Movement",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  14: {
    Type: "Symptom",
    BodyPart: "Abdomen",
    IconName: "Svg025Vomiting",
    Category: "Gastrointestinal",
    Name: "Vomiting",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  15: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg043FoodScale",
    Category: "General",
    Name: "Anorexia",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  16: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg043FoodScale",
    Category: "General",
    Name: "Bulimia",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  17: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg039Cold",
    Category: "General",
    Name: "Desire to eat ice, dirt, or other non-food items",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  18: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg037Dizzy",
    Category: "General",
    Name: "Dizziness",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  19: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg023Fever",
    Category: "General",
    Name: "Excessive Sweating",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  20: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg037Dizzy",
    Category: "General",
    Name: "Fatigue",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  21: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg039Cold",
    Category: "General",
    Name: "Feeling Cold",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  22: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg023Fever",
    Category: "General",
    Name: "Fever",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  23: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg023Fever",
    Category: "General",
    Name: "Shivering / Chills",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  24: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg023Fever",
    Category: "General",
    Name: "Swelling",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: true,
      Number: false,
      Options: [],
    },
  },
  25: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg037Dizzy",
    Category: "General",
    Name: "Weakness",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  26: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg021WeightScale",
    Category: "General",
    Name: "Weight Gain",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  27: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg021WeightScale",
    Category: "General",
    Name: "Weight Loss",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  28: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg024MenstrualPain",
    Category: "Gynecological",
    Name: "Menstruation",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [{ title: "Light" }, { title: "Med" }, { title: "Heavy" }],
    },
  },
  29: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg025Sex",
    Category: "Gynecological",
    Name: "Painful intercourse",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  30: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg024MenstrualPain",
    Category: "Gynecological",
    Name: "Pelvic pain (general)",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  31: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg024MenstrualPain",
    Category: "Gynecological",
    Name: "Pelvic pain (left side)",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  32: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg024MenstrualPain",
    Category: "Gynecological",
    Name: "Pelvic pain (right side)",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  33: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg060Drop",
    Category: "Gynecological",
    Name: "Spotting",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  34: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg030Vaginal",
    Category: "Gynecological",
    Name: "Vaginal discharge",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [
        "none / dry",
        "creamy",
        "watery/ clear",
        "egg white",
        "pale yellow / neon green",
        "gray",
        "pink",
        "red",
      ],
    },
  },
  35: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Acne",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  36: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Bruising",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: true,
      Number: false,
      Options: [],
    },
  },
  37: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Dark Skin Patches",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  38: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Dry Skin",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  39: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg030Hairdressing",
    Category: "Hair, Skin & Nails",
    Name: "Excessive Body Hair",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  40: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg030Hairdressing",
    Category: "Hair, Skin & Nails",
    Name: "Excessive Facial Hair",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  41: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Oily Skin",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  42: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Pale skin",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  43: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg005Rash",
    Category: "Hair, Skin & Nails",
    Name: "Skin Tags",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  44: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg030Hairdressing",
    Category: "Hair, Skin & Nails",
    Name: "Thinning Hair on Head",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  45: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "SvgSolid036ChestPain",
    Category: "Joints & Muscles",
    Name: "Body Aches (general)",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  46: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg022Leg",
    Category: "Joints & Muscles",
    Name: "Leg Pain",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  47: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "SvgSolid036ChestPain",
    Category: "Joints & Muscles",
    Name: "Lower Back Pain",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  48: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "SvgSolid036ChestPain",
    Category: "Joints & Muscles",
    Name: "Other Body Pain",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: true,
      Number: false,
      Options: [],
    },
  },
  49: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg031Sadness",
    Category: "Mental",
    Name: "Anxiety",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  50: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg031Sadness",
    Category: "Mental",
    Name: "Anxiety Attack",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  51: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg031Sadness",
    Category: "Mental",
    Name: "Depression",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  52: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg015MentalHealth",
    Category: "Mental",
    Name: "Irritability",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  53: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg015MentalHealth",
    Category: "Mental",
    Name: "OCD",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  54: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg015MentalHealth",
    Category: "Mental",
    Name: "Painic Attack",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  55: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg015MentalHealth",
    Category: "Mental",
    Name: "Suicidal Thoughts",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  56: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg019Cold",
    Category: "Neurological",
    Name: "Cold extremeities",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  57: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg025Sleep",
    Category: "Neurological",
    Name: "Difficulty Sleeping",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  58: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg025Sleep",
    Category: "Neurological",
    Name: "Drowsiness",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  59: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg037Dizzy",
    Category: "Neurological",
    Name: "Fainting",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  60: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg020Headache",
    Category: "Neurological",
    Name: "Headache",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  61: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg020Headache",
    Category: "Neurological",
    Name: "Lightheadedness",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  62: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg020Headache",
    Category: "Neurological",
    Name: "Migraine",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  63: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg006Neck",
    Category: "Neurological",
    Name: "Neck Stiffness",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  64: {
    Type: "Symptom",
    BodyPart: "",
    IconName: "Svg036Sleep",
    Category: "Neurological",
    Name: "Sleeping Too Much",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  65: {
    Type: "Symptom",
    BodyPart: "Chest",
    IconName: "Svg036ChestPain",
    Category: "Respiratory",
    Name: "Chest Pain",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  66: {
    Type: "Symptom",
    BodyPart: "Chest",
    IconName: "Svg050Cough",
    Category: "Respiratory",
    Name: "Cough",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  67: {
    Type: "Symptom",
    BodyPart: "Chest",
    IconName: "Svg002DifficultyBreathing",
    Category: "Respiratory",
    Name: "Difficulty Breathing",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  68: {
    Type: "Symptom",
    BodyPart: "Chest",
    IconName: "Svg002DifficultyBreathing",
    Category: "Respiratory",
    Name: "Rapid Breathing",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  69: {
    Type: "Symptom",
    BodyPart: "Chest",
    IconName: "Svg002DifficultyBreathing",
    Category: "Respiratory",
    Name: "Shortness of Breath",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  70: {
    Type: "Symptom",
    BodyPart: "Chest",
    IconName: "Svg009Sleep",
    Category: "Respiratory",
    Name: "Sleep Apnea",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  71: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg032DarkUrine",
    Category: "Urinary",
    Name: "Blood in Urine",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  72: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg032DarkUrine",
    Category: "Urinary",
    Name: "Difficulty Emptying Bladder",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  73: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg032DarkUrine",
    Category: "Urinary",
    Name: "Frequent Urination",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  74: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg032DarkUrine",
    Category: "Urinary",
    Name: "Infrequent Urination",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  75: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg032DarkUrine",
    Category: "Urinary",
    Name: "Painful Urination",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  76: {
    Type: "Symptom",
    BodyPart: "Pelvis",
    IconName: "Svg019Incontinence",
    Category: "Urinary",
    Name: "Urinary Incontinence",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  77: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg049WeightScale",
    Category: "General",
    Name: "Weight",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  78: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg049Temperature",
    Category: "General",
    Name: "Basal Body Temperature",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  79: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg011F",
    Category: "General",
    Name: "FSH Level",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  80: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg010L",
    Category: "General",
    Name: "LH Level",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  81: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg035E",
    Category: "General",
    Name: "Estrogen",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  82: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg031P",
    Category: "General",
    Name: "Progesterone",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  83: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg035PregnancyTest",
    Category: "General",
    Name: "Pregnancy Test - Urine",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [{ title: "Yes" }, { title: "No" }, { title: "Inconclusive" }],
    },
  },
  84: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg031BloodTest",
    Category: "General",
    Name: "Pregnancy Test - Blood",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [{ title: "Yes" }, { title: "No" }, { title: "Inconclusive" }],
    },
  },
  85: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg030UrineTest",
    Category: "General",
    Name: "Ovulation Test - Urine",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [{ title: "Yes" }, { title: "No" }, { title: "Inconclusive" }],
    },
  },
  86: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg032TestTube",
    Category: "General",
    Name: "Ovulation Test - Saliva",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [{ title: "Yes" }, { title: "No" }, { title: "Inconclusive" }],
    },
  },
  87: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg023HeartRate",
    Category: "General",
    Name: "Heart Rate",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  88: {
    Type: "HealthMeasurement",
    BodyPart: "",
    IconName: "Svg003BloodPressureGauge",
    Category: "General",
    Name: "Blood Pressure",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: true,
      Options: [],
    },
  },
  89: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg002YogaPose",
    Category: "Activities",
    Name: "Yoga",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  90: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg039Exercise",
    Category: "Activities",
    Name: "Moderate Exercise",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  91: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg039Exercise",
    Category: "Activities",
    Name: "High Intensity Exercise",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  92: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg025Sex",
    Category: "Activities",
    Name: "Sex",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  93: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg075Bed",
    Category: "Activities",
    Name: "Masturbation",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  94: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg041Family",
    Category: "Activities",
    Name: "Spent time with family",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  95: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg026Friends",
    Category: "Activities",
    Name: "Spent time with friends",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  96: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg006Alone",
    Category: "Activities",
    Name: "Spent time alone",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  97: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg018Stressed",
    Category: "Activities",
    Name: "Stressful workday",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  98: {
    Type: "Activity",
    BodyPart: "",
    IconName: "Svg065TvScreen",
    Category: "Activities",
    Name: "Significant screen time",
    Measurements: {
      Binary: true,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  99: {
    Type: "Menstrual",
    BodyPart: "",
    IconName: "Svg028Star",
    Category: "Other",
    Name: "Menstrual Flow",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  0: {
    Type: "Menstrual",
    BodyPart: "",
    IconName: "Svg028Star",
    Category: "Other",
    Name: "Vaginal Discharge",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  100: {
    Type: "Essential",
    BodyPart: "",
    IconName: "Svg028Star",
    Category: "Other",
    Name: "Current Mood",
    Measurements: {
      Binary: false,
      Severity: false,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  101: {
    Type: "Essential",
    BodyPart: "",
    IconName: "Svg028Star",
    Category: "Other",
    Name: "Current Stress",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
  102: {
    Type: "Essential",
    BodyPart: "",
    IconName: "Svg028Star",
    Category: "Other",
    Name: "Current Pain",
    Measurements: {
      Binary: false,
      Severity: true,
      Location: false,
      Number: false,
      Options: [],
    },
  },
};

export default SymptomsDir;
