import Images from "../../constants/Images";
import Animations from "../../constants/Animations";

export const gardenItemsList = [
  // {
  //   type: "flower",
  //   action: "plant",
  //   name: "Associado1",
  //   assets: {
  //     generalStaticImage: Images.garden.flower0_2,
  //     health0StaticImage: Images.garden.flower0_0,
  //     health1StaticImage: Images.garden.flower0_1,
  //     health2StaticImage: Images.garden.flower0_2,
  //     health3StaticImage: Images.garden.flower0_3,

  //     health0Animation: Animations.garden.flower.associado1,
  //     health1Animation: Animations.garden.flower.associado1,
  //     health2Animation: Animations.garden.flower.associado1,
  //     health3Animation: Animations.garden.flower.associado1,
  //   },
  //   rarity: 0.9,
  //   price: 3,
  // },

  {
    itemType: "flower",
    action: "plant",
    name: "Rose1",
    assets: {
      generalStaticImage: Images.garden.flower1_2,
      health0StaticImage: Images.garden.flower1_0,
      health1StaticImage: Images.garden.flower1_1,
      health2StaticImage: Images.garden.flower1_2,
      health3StaticImage: Images.garden.flower1_3,

      health0Animation: "Animations.garden.flower.rose1",
      health1Animation: "Animations.garden.flower.rose1",
      health2Animation: "Animations.garden.flower.rose1",
      health3Animation: "Animations.garden.flower.rose1",
    },
    rarity: 0.6,
    price: 30,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "TreePlant1",
    assets: {
      generalStaticImage: Images.garden.flower2_2,
      health0StaticImage: Images.garden.flower2_0,
      health1StaticImage: Images.garden.flower2_1,
      health2StaticImage: Images.garden.flower2_2,
      health3StaticImage: Images.garden.flower2_3,

      health0Animation: "Animations.garden.flower.treeplant1",
      health1Animation: "Animations.garden.flower.treeplant1",
      health2Animation: "Animations.garden.flower.treeplant1",
      health3Animation: "Animations.garden.flower.treeplant1",
    },
    rarity: 0.1,
    price: 150,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "WindPlant1",
    assets: {
      generalStaticImage: Images.garden.flower3_2,
      health0StaticImage: Images.garden.flower3_0,
      health1StaticImage: Images.garden.flower3_1,
      health2StaticImage: Images.garden.flower3_2,
      health3StaticImage: Images.garden.flower3_3,

      health0Animation: "Animations.garden.flower.windPlant1",
      health1Animation: "Animations.garden.flower.windPlant1",
      health2Animation: "Animations.garden.flower.windPlant1",
      health3Animation: "Animations.garden.flower.windPlant1",
    },
    rarity: 0.8,
    price: 3,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "Plants1",
    assets: {
      generalStaticImage: Images.garden.flower4_2,
      health0StaticImage: Images.garden.flower4_0,
      health1StaticImage: Images.garden.flower4_1,
      health2StaticImage: Images.garden.flower4_2,
      health3StaticImage: Images.garden.flower4_3,

      health0Animation: "Animations.garden.flower.plants1",
      health1Animation: "Animations.garden.flower.plants1",
      health2Animation: "Animations.garden.flower.plants1",
      health3Animation: "Animations.garden.flower.plants1",
    },
    rarity: 0.1,
    price: 120,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "FloralButterfly1",
    assets: {
      generalStaticImage: Images.garden.flower5_2,
      health0StaticImage: Images.garden.flower5_0,
      health1StaticImage: Images.garden.flower5_1,
      health2StaticImage: Images.garden.flower5_2,
      health3StaticImage: Images.garden.flower5_3,

      health0Animation: "Animations.garden.flower.floralButterfly1",
      health1Animation: "Animations.garden.flower.floralButterfly1",
      health2Animation: "Animations.garden.flower.floralButterfly1",
      health3Animation: "Animations.garden.flower.floralButterfly1",
    },
    rarity: 0.5,
    price: 50,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "Flower1",
    assets: {
      generalStaticImage: Images.garden.flower6_2,
      health0StaticImage: Images.garden.flower6_0,
      health1StaticImage: Images.garden.flower6_1,
      health2StaticImage: Images.garden.flower6_2,
      health3StaticImage: Images.garden.flower6_3,

      health0Animation: "Animations.garden.flower.flower1",
      health1Animation: "Animations.garden.flower.flower1",
      health2Animation: "Animations.garden.flower.flower1",
      health3Animation: "Animations.garden.flower.flower1",
    },
    rarity: 0.6,
    price: 60,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "PlantLaranga1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.plantaLaranja1",
      health1Animation: "Animations.garden.flower.plantaLaranja1",
      health2Animation: "Animations.garden.flower.plantaLaranja1",
      health3Animation: "Animations.garden.flower.plantaLaranja1",
    },
    rarity: 0.3,
    price: 10,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Flower2",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flower2",
      health1Animation: "Animations.garden.flower.flower2",
      health2Animation: "Animations.garden.flower.flower2",
      health3Animation: "Animations.garden.flower.flower2",
    },
    rarity: 0.7,
    price: 50,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "GreenFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.greenFlower1",
      health1Animation: "Animations.garden.flower.greenFlower1",
      health2Animation: "Animations.garden.flower.greenFlower1",
      health3Animation: "Animations.garden.flower.greenFlower1",
    },
    rarity: 0.96,
    price: 3,
  },
  // {
  //   itemType: "flower",
  //   action: "plant",
  //   name: "PottedPlant1",
  //   assets: {
  //     generalStaticImage: Images.garden.flower7_2,
  //     health0StaticImage: Images.garden.flower7_0,
  //     health1StaticImage: Images.garden.flower7_1,
  //     health2StaticImage: Images.garden.flower7_2,
  //     health3StaticImage: Images.garden.flower7_3,

  //     health0Animation: Animations.garden.flower.animatedPlantInPot1,
  //     health1Animation: Animations.garden.flower.animatedPlantInPot1,
  //     health2Animation: Animations.garden.flower.animatedPlantInPot1,
  //     health3Animation: Animations.garden.flower.animatedPlantInPot1,
  //   },
  //   rarity: 0.3,
  //   price: 40,
  // },
  {
    itemType: "flower",
    action: "plant",
    name: "PlantAnim1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.plantAnimation1",
      health1Animation: "Animations.garden.flower.plantAnimation1",
      health2Animation: "Animations.garden.flower.plantAnimation1",
      health3Animation: "Animations.garden.flower.plantAnimation1",
    },
    rarity: 0.1,
    price: 70,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "Plant123",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.plant123",
      health1Animation: "Animations.garden.flower.plant123",
      health2Animation: "Animations.garden.flower.plant123",
      health3Animation: "Animations.garden.flower.plant123",
    },
    rarity: 0.2,
    price: 30,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "PlantMov1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.plantMoving1",
      health1Animation: "Animations.garden.flower.plantMoving1",
      health2Animation: "Animations.garden.flower.plantMoving1",
      health3Animation: "Animations.garden.flower.plantMoving1",
    },
    rarity: 0.95,
    price: 40,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "OrganePlant1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.orangePlant1",
      health1Animation: "Animations.garden.flower.orangePlant1",
      health2Animation: "Animations.garden.flower.orangePlant1",
      health3Animation: "Animations.garden.flower.orangePlant1",
    },
    rarity: 0.6,
    price: 60,
  },
  // {
  //   itemType: "flower",
  //   action: "plant",
  //   name: "Plant2",
  //   assets: {
  //     generalStaticImage: Images.garden.flower7_2,
  //     health0StaticImage: Images.garden.flower7_0,
  //     health1StaticImage: Images.garden.flower7_1,
  //     health2StaticImage: Images.garden.flower7_2,
  //     health3StaticImage: Images.garden.flower7_3,

  //     health0Animation: Animations.garden.flower.plant2,
  //     health1Animation: Animations.garden.flower.plant2,
  //     health2Animation: Animations.garden.flower.plant2,
  //     health3Animation: Animations.garden.flower.plant2,
  //   },
  //   rarity: 0.9,
  //   price: 3,
  // },
  {
    itemType: "flower",
    action: "plant",
    name: "WheatTwigs1",
    assets: {
      generalStaticImage: Images.garden.flower0_2,
      health0StaticImage: Images.garden.flower0_0,
      health1StaticImage: Images.garden.flower0_1,
      health2StaticImage: Images.garden.flower0_2,
      health3StaticImage: Images.garden.flower0_3,

      health0Animation: "Animations.garden.flower.wheatTwigs1",
      health1Animation: "Animations.garden.flower.wheatTwigs1",
      health2Animation: "Animations.garden.flower.wheatTwigs1",
      health3Animation: "Animations.garden.flower.wheatTwigs1",
    },
    rarity: 0.8,
    price: 30,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "FlowerPlant2",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flowerPlantMoving1",
      health1Animation: "Animations.garden.flower.flowerPlantMoving1",
      health2Animation: "Animations.garden.flower.flowerPlantMoving1",
      health3Animation: "Animations.garden.flower.flowerPlantMoving1",
    },
    rarity: 0.1,
    price: 30,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "FlowerPlant3",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.floweringPlant1",
      health1Animation: "Animations.garden.flower.floweringPlant1",
      health2Animation: "Animations.garden.flower.floweringPlant1",
      health3Animation: "Animations.garden.flower.floweringPlant1",
    },
    rarity: 0.9,
    price: 30,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "FlowerTreePlant1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flowerTreeplant",
      health1Animation: "Animations.garden.flower.flowerTreeplant",
      health2Animation: "Animations.garden.flower.flowerTreeplant",
      health3Animation: "Animations.garden.flower.flowerTreeplant",
    },
    rarity: 0.7,
    price: 50,
  },
  // {
  //   itemType: "flower",
  //   action: "plant",
  //   name: "QRCode1",
  //   assets: {
  //     generalStaticImage: Images.garden.flower7_2,
  //     health0StaticImage: Images.garden.flower7_0,
  //     health1StaticImage: Images.garden.flower7_1,
  //     health2StaticImage: Images.garden.flower7_2,
  //     health3StaticImage: Images.garden.flower7_3,

  //     health0Animation: Animations.garden.flower.qrCode1,
  //     health1Animation: Animations.garden.flower.qrCode1,
  //     health2Animation: Animations.garden.flower.qrCode1,
  //     health3Animation: Animations.garden.flower.qrCode1,
  //   },
  //   rarity: 0.3,
  //   price: 70,
  // },
  // {
  //   itemType: "flower",
  //   action: "plant",
  //   name: "Plant3",
  //   assets: {
  //     generalStaticImage: Images.garden.flower7_2,
  //     health0StaticImage: Images.garden.flower7_0,
  //     health1StaticImage: Images.garden.flower7_1,
  //     health2StaticImage: Images.garden.flower7_2,
  //     health3StaticImage: Images.garden.flower7_3,

  //     health0Animation: Animations.garden.flower.plant3,
  //     health1Animation: Animations.garden.flower.plant3,
  //     health2Animation: Animations.garden.flower.plant3,
  //     health3Animation: Animations.garden.flower.plant3,
  //   },
  //   rarity: 0.9,
  //   price: 40,
  // },
  {
    itemType: "flower",
    action: "plant",
    name: "HousePlant1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.houseplant1",
      health1Animation: "Animations.garden.flower.houseplant1",
      health2Animation: "Animations.garden.flower.houseplant1",
      health3Animation: "Animations.garden.flower.houseplant1",
    },
    rarity: 0.9,
    price: 3,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "Flower3",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flower3",
      health1Animation: "Animations.garden.flower.flower3",
      health2Animation: "Animations.garden.flower.flower3",
      health3Animation: "Animations.garden.flower.flower3",
    },
    rarity: 0.8,
    price: 70,
  },
  {
    itemType: "flower",
    action: "plant",
    name: "BlueFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.blueFlower1",
      health1Animation: "Animations.garden.flower.blueFlower1",
      health2Animation: "Animations.garden.flower.blueFlower1",
      health3Animation: "Animations.garden.flower.blueFlower1",
    },
    rarity: 0.3,
    price: 40,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Aloevera1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.aloevera1",
      health1Animation: "Animations.garden.flower.aloevera1",
      health2Animation: "Animations.garden.flower.aloevera1",
      health3Animation: "Animations.garden.flower.aloevera1",
    },
    rarity: 0.1,
    price: 80,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Bamboo1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.bamboo1",
      health1Animation: "Animations.garden.flower.bamboo1",
      health2Animation: "Animations.garden.flower.bamboo1",
      health3Animation: "Animations.garden.flower.bamboo1",
    },
    rarity: 0.1,
    price: 3,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "BlossonTree1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.blossonTree1",
      health1Animation: "Animations.garden.flower.blossonTree1",
      health2Animation: "Animations.garden.flower.blossonTree1",
      health3Animation: "Animations.garden.flower.blossonTree1",
    },
    rarity: 0.1,
    price: 100,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "BorageFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.borageFlower1",
      health1Animation: "Animations.garden.flower.borageFlower1",
      health2Animation: "Animations.garden.flower.borageFlower1",
      health3Animation: "Animations.garden.flower.borageFlower1",
    },
    rarity: 0.1,
    price: 80,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Cactus1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.cactus1",
      health1Animation: "Animations.garden.flower.cactus1",
      health2Animation: "Animations.garden.flower.cactus1",
      health3Animation: "Animations.garden.flower.cactus1",
    },
    rarity: 0.1,
    price: 40,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Cactus2",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.cactus2",
      health1Animation: "Animations.garden.flower.cactus2",
      health2Animation: "Animations.garden.flower.cactus2",
      health3Animation: "Animations.garden.flower.cactus2",
    },
    rarity: 0.1,
    price: 50,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "ChamomileFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.chamomileFlower1",
      health1Animation: "Animations.garden.flower.chamomileFlower1",
      health2Animation: "Animations.garden.flower.chamomileFlower1",
      health3Animation: "Animations.garden.flower.chamomileFlower1",
    },
    rarity: 0.1,
    price: 60,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "CloverFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.cloverFlower1",
      health1Animation: "Animations.garden.flower.cloverFlower1",
      health2Animation: "Animations.garden.flower.cloverFlower1",
      health3Animation: "Animations.garden.flower.cloverFlower1",
    },
    rarity: 0.1,
    price: 70,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "CornPlant1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.cornPlant1",
      health1Animation: "Animations.garden.flower.cornPlant1",
      health2Animation: "Animations.garden.flower.cornPlant1",
      health3Animation: "Animations.garden.flower.cornPlant1",
    },
    rarity: 0.1,
    price: 100,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Flower4",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flower4",
      health1Animation: "Animations.garden.flower.flower4",
      health2Animation: "Animations.garden.flower.flower4",
      health3Animation: "Animations.garden.flower.flower4",
    },
    rarity: 0.1,
    price: 100,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Flower5",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flower5",
      health1Animation: "Animations.garden.flower.flower5",
      health2Animation: "Animations.garden.flower.flower5",
      health3Animation: "Animations.garden.flower.flower5",
    },
    rarity: 0.1,
    price: 90,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Flower6",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flower6",
      health1Animation: "Animations.garden.flower.flower6",
      health2Animation: "Animations.garden.flower.flower6",
      health3Animation: "Animations.garden.flower.flower6",
    },
    rarity: 0.1,
    price: 80,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "FlowerPot1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flowerPot1",
      health1Animation: "Animations.garden.flower.flowerPot1",
      health2Animation: "Animations.garden.flower.flowerPot1",
      health3Animation: "Animations.garden.flower.flowerPot1",
    },
    rarity: 0.1,
    price: 110,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "FlowerVase1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.flowerVase1",
      health1Animation: "Animations.garden.flower.flowerVase1",
      health2Animation: "Animations.garden.flower.flowerVase1",
      health3Animation: "Animations.garden.flower.flowerVase1",
    },
    rarity: 0.1,
    price: 100,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Gardening1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.gardening1",
      health1Animation: "Animations.garden.flower.gardening1",
      health2Animation: "Animations.garden.flower.gardening1",
      health3Animation: "Animations.garden.flower.gardening1",
    },
    rarity: 0.1,
    price: 80,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Grass1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.grass1",
      health1Animation: "Animations.garden.flower.grass1",
      health2Animation: "Animations.garden.flower.grass1",
      health3Animation: "Animations.garden.flower.grass1",
    },
    rarity: 0.1,
    price: 90,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "LotusFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.lotusFlower1",
      health1Animation: "Animations.garden.flower.lotusFlower1",
      health2Animation: "Animations.garden.flower.lotusFlower1",
      health3Animation: "Animations.garden.flower.lotusFlower1",
    },
    rarity: 0.1,
    price: 80,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "PansyFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.pansyFlower1",
      health1Animation: "Animations.garden.flower.pansyFlower1",
      health2Animation: "Animations.garden.flower.pansyFlower1",
      health3Animation: "Animations.garden.flower.pansyFlower1",
    },
    rarity: 0.1,
    price: 70,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "PinkFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.pinkFlower1",
      health1Animation: "Animations.garden.flower.pinkFlower1",
      health2Animation: "Animations.garden.flower.pinkFlower1",
      health3Animation: "Animations.garden.flower.pinkFlower1",
    },
    rarity: 0.1,
    price: 140,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "PlantPot2",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.plantPot2",
      health1Animation: "Animations.garden.flower.plantPot2",
      health2Animation: "Animations.garden.flower.plantPot2",
      health3Animation: "Animations.garden.flower.plantPot2",
    },
    rarity: 0.1,
    price: 120,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "RoseFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.roseFlower1",
      health1Animation: "Animations.garden.flower.roseFlower1",
      health2Animation: "Animations.garden.flower.roseFlower1",
      health3Animation: "Animations.garden.flower.roseFlower1",
    },
    rarity: 0.1,
    price: 110,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "SeedlingFlowers1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.seedlingFlowers1",
      health1Animation: "Animations.garden.flower.seedlingFlowers1",
      health2Animation: "Animations.garden.flower.seedlingFlowers1",
      health3Animation: "Animations.garden.flower.seedlingFlowers1",
    },
    rarity: 0.1,
    price: 60,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "SpaFlower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.spaFlower1",
      health1Animation: "Animations.garden.flower.spaFlower1",
      health2Animation: "Animations.garden.flower.spaFlower1",
      health3Animation: "Animations.garden.flower.spaFlower1",
    },
    rarity: 0.1,
    price: 70,
  },

  {
    itemType: "flower",
    action: "plant",
    name: "Sunflower1",
    assets: {
      generalStaticImage: Images.garden.flower7_2,
      health0StaticImage: Images.garden.flower7_0,
      health1StaticImage: Images.garden.flower7_1,
      health2StaticImage: Images.garden.flower7_2,
      health3StaticImage: Images.garden.flower7_3,

      health0Animation: "Animations.garden.flower.sunflower1",
      health1Animation: "Animations.garden.flower.sunflower1",
      health2Animation: "Animations.garden.flower.sunflower1",
      health3Animation: "Animations.garden.flower.sunflower1",
    },
    rarity: 0.1,
    price: 90,
  },
];

// {"itemType": ["flower", "deco", "garden", "dye", "badge", "weed"],
// "action": ["plant", "dye", "decoGeneral", "decoSpecific"],
// "name": "TMP",
// "assets": {"staticImage": "TMP"},
// "rarity": 0.0,
// "price": 20
// },
